#!/bin/bash

set -ex

# Wait for cloud-init to finish.
#echo "Waiting 180 seconds for cloud-init to complete."
#timeout 180 /bin/bash -c \
#  'until stat /var/lib/cloud/instance/boot-finished 2>/dev/null; do echo "Waiting ..."; sleep 2; done'

NOMAD_VERSION=0.8.4


INSTANCE_ID=$HOSTNAME
INSTANCE_PRIVATE_IP=$(ifconfig ens4 | grep "inet addr" | awk '{ print substr($2,6) }')

sudo apt-get -qq -y update

#######################################
# NOMAD INSTALL
#######################################

# install dependencies
echo "Installing dependencies..."
sudo apt-get install -qq -y wget unzip

# install nomad
echo "Fetching nomad..."
cd /tmp/

wget -q https://releases.hashicorp.com/nomad/0.8.4/nomad_0.8.4_linux_amd64.zip -O nomad.zip

echo "Installing nomad..."
unzip nomad.zip
rm nomad.zip
sudo chmod +x nomad
sudo mv nomad /usr/bin/nomad
sudo mkdir -pm 0600 /etc/nomad.d

# setup nomad directories
sudo mkdir -pm 0600 /var/nomad
sudo mkdir -p /var/nomad/data

echo "Nomad installation complete."

#######################################
# NOMAD CONFIGURATION
#######################################

sudo tee /etc/nomad.d/nomad.hcl > /dev/null <<EOF
name       = "$INSTANCE_ID"
data_dir   = "/var/nomad/data"
datacenter = "DC1"
bind_addr = "0.0.0.0"
client {
  enabled = true
  network_interface = "bond0"
}
addresses {
  rpc  = "$INSTANCE_PRIVATE_IP"
  serf = "$INSTANCE_PRIVATE_IP"
}
advertise {
  http = "$INSTANCE_PRIVATE_IP:4646"
}
consul {
}
EOF

echo " ===> Installing init script"

cat >/etc/systemd/system/nomad.service <<EOF
[Unit]
Description=Nomad agent
Requires=network-online.target
After=network-online.target
[Service]
EnvironmentFile=-/etc/sysconfig/nomad
Environment=GOMAXPROCS=2
Restart=on-failure
ExecStart=/bin/bash -ce "exec /usr/bin/nomad agent -config /etc/nomad.d/ >>/var/log/nomad.log 2>&1"
ExecReload=/bin/kill -HUP
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
TimeoutStartSec=0
KillSignal=SIGINT
[Install]
WantedBy=multi-user.target
EOF
echo " ===> Starting nomad"
systemctl enable nomad.service
systemctl daemon-reload

echo " ===> Starting nomad"
service nomad start
